// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Tracing implementation internals
#include "verilated_vcd_c.h"
#include "Vtb_mem_soc__Syms.h"


VL_ATTR_COLD void Vtb_mem_soc___024root__trace_init_sub__TOP__0(Vtb_mem_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_mem_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_mem_soc___024root__trace_init_sub__TOP__0\n"); );
    // Init
    const int c = vlSymsp->__Vm_baseCode;
    // Body
    tracep->pushNamePrefix("tb_mem_soc ");
    tracep->declBus(c+317,"CLK_PERIOD", false,-1, 31,0);
    tracep->declBus(c+318,"UART_BIT_CYCLES", false,-1, 31,0);
    tracep->declBus(c+319,"BAUD_HALF", false,-1, 31,0);
    tracep->declBus(c+320,"BAUD_FULL", false,-1, 31,0);
    tracep->declBus(c+321,"TIMEOUT_NS", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBus(c+34,"greeting_count", false,-1, 31,0);
    tracep->declBus(c+35,"line_count", false,-1, 31,0);
    tracep->declBit(c+48,"uart_tx_pin", false,-1);
    tracep->declBit(c+322,"uart_rx_pin", false,-1);
    tracep->declBus(c+36,"rx_wr_ptr", false,-1, 31,0);
    tracep->declBus(c+37,"mon_byte", false,-1, 7,0);
    tracep->declBus(c+38,"bit_idx", false,-1, 31,0);
    tracep->declArray(c+39,"asm_line", false,-1, 255,0);
    tracep->declBus(c+47,"asm_len", false,-1, 31,0);
    tracep->pushNamePrefix("u_dut ");
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBit(c+48,"uart_tx", false,-1);
    tracep->declBit(c+322,"uart_rx", false,-1);
    tracep->declBit(c+77,"cpu_mem_valid", false,-1);
    tracep->declBit(c+78,"cpu_mem_instr", false,-1);
    tracep->declBit(c+311,"cpu_mem_ready", false,-1);
    tracep->declBus(c+79,"cpu_mem_addr", false,-1, 31,0);
    tracep->declBus(c+80,"cpu_mem_wdata", false,-1, 31,0);
    tracep->declBus(c+81,"cpu_mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+305,"cpu_mem_rdata", false,-1, 31,0);
    tracep->declBit(c+82,"sel_rom", false,-1);
    tracep->declBit(c+83,"sel_sram", false,-1);
    tracep->declBit(c+84,"sel_uart", false,-1);
    tracep->declBit(c+82,"rom_valid", false,-1);
    tracep->declBit(c+83,"sram_valid", false,-1);
    tracep->declBit(c+84,"uart_valid", false,-1);
    tracep->declBit(c+49,"rom_ready", false,-1);
    tracep->declBus(c+50,"rom_rdata", false,-1, 31,0);
    tracep->declBit(c+51,"sram_ready", false,-1);
    tracep->declBus(c+52,"sram_rdata", false,-1, 31,0);
    tracep->declBit(c+53,"uart_ready", false,-1);
    tracep->declBus(c+54,"uart_rdata", false,-1, 31,0);
    tracep->pushNamePrefix("u_cpu ");
    tracep->declBus(c+323,"ENABLE_COUNTERS", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_COUNTERS64", false,-1, 0,0);
    tracep->declBus(c+323,"ENABLE_REGS_16_31", false,-1, 0,0);
    tracep->declBus(c+323,"ENABLE_REGS_DUALPORT", false,-1, 0,0);
    tracep->declBus(c+324,"LATCHED_MEM_RDATA", false,-1, 0,0);
    tracep->declBus(c+323,"TWO_STAGE_SHIFT", false,-1, 0,0);
    tracep->declBus(c+324,"BARREL_SHIFTER", false,-1, 0,0);
    tracep->declBus(c+324,"TWO_CYCLE_COMPARE", false,-1, 0,0);
    tracep->declBus(c+324,"TWO_CYCLE_ALU", false,-1, 0,0);
    tracep->declBus(c+324,"COMPRESSED_ISA", false,-1, 0,0);
    tracep->declBus(c+323,"CATCH_MISALIGN", false,-1, 0,0);
    tracep->declBus(c+323,"CATCH_ILLINSN", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_PCPI", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_MUL", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_FAST_MUL", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_DIV", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_IRQ", false,-1, 0,0);
    tracep->declBus(c+323,"ENABLE_IRQ_QREGS", false,-1, 0,0);
    tracep->declBus(c+323,"ENABLE_IRQ_TIMER", false,-1, 0,0);
    tracep->declBus(c+324,"ENABLE_TRACE", false,-1, 0,0);
    tracep->declBus(c+324,"REGS_INIT_ZERO", false,-1, 0,0);
    tracep->declBus(c+325,"MASKED_IRQ", false,-1, 31,0);
    tracep->declBus(c+326,"LATCHED_IRQ", false,-1, 31,0);
    tracep->declBus(c+325,"PROGADDR_RESET", false,-1, 31,0);
    tracep->declBus(c+327,"PROGADDR_IRQ", false,-1, 31,0);
    tracep->declBus(c+328,"STACKADDR", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+312,"resetn", false,-1);
    tracep->declBit(c+85,"trap", false,-1);
    tracep->declBit(c+77,"mem_valid", false,-1);
    tracep->declBit(c+78,"mem_instr", false,-1);
    tracep->declBit(c+311,"mem_ready", false,-1);
    tracep->declBus(c+79,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+80,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+81,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+305,"mem_rdata", false,-1, 31,0);
    tracep->declBit(c+313,"mem_la_read", false,-1);
    tracep->declBit(c+314,"mem_la_write", false,-1);
    tracep->declBus(c+86,"mem_la_addr", false,-1, 31,0);
    tracep->declBus(c+87,"mem_la_wdata", false,-1, 31,0);
    tracep->declBus(c+88,"mem_la_wstrb", false,-1, 3,0);
    tracep->declBit(c+89,"pcpi_valid", false,-1);
    tracep->declBus(c+90,"pcpi_insn", false,-1, 31,0);
    tracep->declBus(c+91,"pcpi_rs1", false,-1, 31,0);
    tracep->declBus(c+92,"pcpi_rs2", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_wr", false,-1);
    tracep->declBus(c+325,"pcpi_rd", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_wait", false,-1);
    tracep->declBit(c+329,"pcpi_ready", false,-1);
    tracep->declBus(c+325,"irq", false,-1, 31,0);
    tracep->declBus(c+93,"eoi", false,-1, 31,0);
    tracep->declBit(c+94,"trace_valid", false,-1);
    tracep->declQuad(c+95,"trace_data", false,-1, 35,0);
    tracep->declBus(c+330,"irq_timer", false,-1, 31,0);
    tracep->declBus(c+331,"irq_ebreak", false,-1, 31,0);
    tracep->declBus(c+332,"irq_buserror", false,-1, 31,0);
    tracep->declBus(c+333,"irqregs_offset", false,-1, 31,0);
    tracep->declBus(c+333,"regfile_size", false,-1, 31,0);
    tracep->declBus(c+334,"regindex_bits", false,-1, 31,0);
    tracep->declBus(c+324,"WITH_PCPI", false,-1, 0,0);
    tracep->declQuad(c+335,"TRACE_BRANCH", false,-1, 35,0);
    tracep->declQuad(c+337,"TRACE_ADDR", false,-1, 35,0);
    tracep->declQuad(c+339,"TRACE_IRQ", false,-1, 35,0);
    tracep->declQuad(c+97,"count_cycle", false,-1, 63,0);
    tracep->declQuad(c+99,"count_instr", false,-1, 63,0);
    tracep->declBus(c+101,"reg_pc", false,-1, 31,0);
    tracep->declBus(c+102,"reg_next_pc", false,-1, 31,0);
    tracep->declBus(c+91,"reg_op1", false,-1, 31,0);
    tracep->declBus(c+92,"reg_op2", false,-1, 31,0);
    tracep->declBus(c+103,"reg_out", false,-1, 31,0);
    tracep->declBus(c+104,"reg_sh", false,-1, 4,0);
    tracep->declBus(c+105,"next_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+106,"dbg_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+107,"dbg_insn_addr", false,-1, 31,0);
    tracep->declBit(c+77,"dbg_mem_valid", false,-1);
    tracep->declBit(c+78,"dbg_mem_instr", false,-1);
    tracep->declBit(c+311,"dbg_mem_ready", false,-1);
    tracep->declBus(c+79,"dbg_mem_addr", false,-1, 31,0);
    tracep->declBus(c+80,"dbg_mem_wdata", false,-1, 31,0);
    tracep->declBus(c+81,"dbg_mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+305,"dbg_mem_rdata", false,-1, 31,0);
    tracep->declBus(c+108,"next_pc", false,-1, 31,0);
    tracep->declBit(c+109,"irq_delay", false,-1);
    tracep->declBit(c+110,"irq_active", false,-1);
    tracep->declBus(c+111,"irq_mask", false,-1, 31,0);
    tracep->declBus(c+112,"irq_pending", false,-1, 31,0);
    tracep->declBus(c+113,"timer", false,-1, 31,0);
    for (int i = 0; i < 32; ++i) {
        tracep->declBus(c+114+i*1,"cpuregs", true,(i+0), 31,0);
    }
    tracep->declBus(c+341,"i", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_mul_wr", false,-1);
    tracep->declBus(c+325,"pcpi_mul_rd", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_mul_wait", false,-1);
    tracep->declBit(c+329,"pcpi_mul_ready", false,-1);
    tracep->declBit(c+329,"pcpi_div_wr", false,-1);
    tracep->declBus(c+325,"pcpi_div_rd", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_div_wait", false,-1);
    tracep->declBit(c+329,"pcpi_div_ready", false,-1);
    tracep->declBit(c+329,"pcpi_int_wr", false,-1);
    tracep->declBus(c+325,"pcpi_int_rd", false,-1, 31,0);
    tracep->declBit(c+329,"pcpi_int_wait", false,-1);
    tracep->declBit(c+329,"pcpi_int_ready", false,-1);
    tracep->declBus(c+146,"mem_state", false,-1, 1,0);
    tracep->declBus(c+147,"mem_wordsize", false,-1, 1,0);
    tracep->declBus(c+306,"mem_rdata_word", false,-1, 31,0);
    tracep->declBus(c+148,"mem_rdata_q", false,-1, 31,0);
    tracep->declBit(c+149,"mem_do_prefetch", false,-1);
    tracep->declBit(c+150,"mem_do_rinst", false,-1);
    tracep->declBit(c+151,"mem_do_rdata", false,-1);
    tracep->declBit(c+152,"mem_do_wdata", false,-1);
    tracep->declBit(c+307,"mem_xfer", false,-1);
    tracep->declBit(c+153,"mem_la_secondword", false,-1);
    tracep->declBit(c+154,"mem_la_firstword_reg", false,-1);
    tracep->declBit(c+155,"last_mem_valid", false,-1);
    tracep->declBit(c+329,"mem_la_firstword", false,-1);
    tracep->declBit(c+329,"mem_la_firstword_xfer", false,-1);
    tracep->declBit(c+156,"prefetched_high_word", false,-1);
    tracep->declBit(c+315,"clear_prefetched_high_word", false,-1);
    tracep->declBus(c+342,"mem_16bit_buffer", false,-1, 15,0);
    tracep->declBus(c+308,"mem_rdata_latched_noshuffle", false,-1, 31,0);
    tracep->declBus(c+308,"mem_rdata_latched", false,-1, 31,0);
    tracep->declBit(c+329,"mem_la_use_prefetched_high_word", false,-1);
    tracep->declBit(c+157,"mem_busy", false,-1);
    tracep->declBit(c+316,"mem_done", false,-1);
    tracep->declBit(c+158,"instr_lui", false,-1);
    tracep->declBit(c+159,"instr_auipc", false,-1);
    tracep->declBit(c+160,"instr_jal", false,-1);
    tracep->declBit(c+161,"instr_jalr", false,-1);
    tracep->declBit(c+162,"instr_beq", false,-1);
    tracep->declBit(c+163,"instr_bne", false,-1);
    tracep->declBit(c+164,"instr_blt", false,-1);
    tracep->declBit(c+165,"instr_bge", false,-1);
    tracep->declBit(c+166,"instr_bltu", false,-1);
    tracep->declBit(c+167,"instr_bgeu", false,-1);
    tracep->declBit(c+168,"instr_lb", false,-1);
    tracep->declBit(c+169,"instr_lh", false,-1);
    tracep->declBit(c+170,"instr_lw", false,-1);
    tracep->declBit(c+171,"instr_lbu", false,-1);
    tracep->declBit(c+172,"instr_lhu", false,-1);
    tracep->declBit(c+173,"instr_sb", false,-1);
    tracep->declBit(c+174,"instr_sh", false,-1);
    tracep->declBit(c+175,"instr_sw", false,-1);
    tracep->declBit(c+176,"instr_addi", false,-1);
    tracep->declBit(c+177,"instr_slti", false,-1);
    tracep->declBit(c+178,"instr_sltiu", false,-1);
    tracep->declBit(c+179,"instr_xori", false,-1);
    tracep->declBit(c+180,"instr_ori", false,-1);
    tracep->declBit(c+181,"instr_andi", false,-1);
    tracep->declBit(c+182,"instr_slli", false,-1);
    tracep->declBit(c+183,"instr_srli", false,-1);
    tracep->declBit(c+184,"instr_srai", false,-1);
    tracep->declBit(c+185,"instr_add", false,-1);
    tracep->declBit(c+186,"instr_sub", false,-1);
    tracep->declBit(c+187,"instr_sll", false,-1);
    tracep->declBit(c+188,"instr_slt", false,-1);
    tracep->declBit(c+189,"instr_sltu", false,-1);
    tracep->declBit(c+190,"instr_xor", false,-1);
    tracep->declBit(c+191,"instr_srl", false,-1);
    tracep->declBit(c+192,"instr_sra", false,-1);
    tracep->declBit(c+193,"instr_or", false,-1);
    tracep->declBit(c+194,"instr_and", false,-1);
    tracep->declBit(c+195,"instr_rdcycle", false,-1);
    tracep->declBit(c+196,"instr_rdcycleh", false,-1);
    tracep->declBit(c+197,"instr_rdinstr", false,-1);
    tracep->declBit(c+198,"instr_rdinstrh", false,-1);
    tracep->declBit(c+199,"instr_ecall_ebreak", false,-1);
    tracep->declBit(c+200,"instr_fence", false,-1);
    tracep->declBit(c+201,"instr_getq", false,-1);
    tracep->declBit(c+202,"instr_setq", false,-1);
    tracep->declBit(c+203,"instr_retirq", false,-1);
    tracep->declBit(c+204,"instr_maskirq", false,-1);
    tracep->declBit(c+205,"instr_waitirq", false,-1);
    tracep->declBit(c+206,"instr_timer", false,-1);
    tracep->declBit(c+207,"instr_trap", false,-1);
    tracep->declBus(c+208,"decoded_rd", false,-1, 4,0);
    tracep->declBus(c+209,"decoded_rs1", false,-1, 4,0);
    tracep->declBus(c+210,"decoded_rs2", false,-1, 4,0);
    tracep->declBus(c+211,"decoded_imm", false,-1, 31,0);
    tracep->declBus(c+212,"decoded_imm_j", false,-1, 31,0);
    tracep->declBit(c+213,"decoder_trigger", false,-1);
    tracep->declBit(c+214,"decoder_trigger_q", false,-1);
    tracep->declBit(c+215,"decoder_pseudo_trigger", false,-1);
    tracep->declBit(c+216,"decoder_pseudo_trigger_q", false,-1);
    tracep->declBit(c+203,"compressed_instr", false,-1);
    tracep->declBit(c+217,"is_lui_auipc_jal", false,-1);
    tracep->declBit(c+218,"is_lb_lh_lw_lbu_lhu", false,-1);
    tracep->declBit(c+219,"is_slli_srli_srai", false,-1);
    tracep->declBit(c+220,"is_jalr_addi_slti_sltiu_xori_ori_andi", false,-1);
    tracep->declBit(c+221,"is_sb_sh_sw", false,-1);
    tracep->declBit(c+222,"is_sll_srl_sra", false,-1);
    tracep->declBit(c+223,"is_lui_auipc_jal_jalr_addi_add_sub", false,-1);
    tracep->declBit(c+224,"is_slti_blt_slt", false,-1);
    tracep->declBit(c+225,"is_sltiu_bltu_sltu", false,-1);
    tracep->declBit(c+226,"is_beq_bne_blt_bge_bltu_bgeu", false,-1);
    tracep->declBit(c+227,"is_lbu_lhu_lw", false,-1);
    tracep->declBit(c+228,"is_alu_reg_imm", false,-1);
    tracep->declBit(c+229,"is_alu_reg_reg", false,-1);
    tracep->declBit(c+230,"is_compare", false,-1);
    tracep->declBit(c+231,"is_rdcycle_rdcycleh_rdinstr_rdinstrh", false,-1);
    tracep->declQuad(c+232,"new_ascii_instr", false,-1, 63,0);
    tracep->declQuad(c+234,"dbg_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+236,"dbg_insn_imm", false,-1, 31,0);
    tracep->declBus(c+237,"dbg_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+238,"dbg_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+239,"dbg_insn_rd", false,-1, 4,0);
    tracep->declBus(c+240,"dbg_rs1val", false,-1, 31,0);
    tracep->declBus(c+241,"dbg_rs2val", false,-1, 31,0);
    tracep->declBit(c+242,"dbg_rs1val_valid", false,-1);
    tracep->declBit(c+243,"dbg_rs2val_valid", false,-1);
    tracep->declQuad(c+244,"q_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+246,"q_insn_imm", false,-1, 31,0);
    tracep->declBus(c+247,"q_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+248,"q_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+249,"q_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+250,"q_insn_rd", false,-1, 4,0);
    tracep->declBit(c+251,"dbg_next", false,-1);
    tracep->declBit(c+252,"launch_next_insn", false,-1);
    tracep->declBit(c+253,"dbg_valid_insn", false,-1);
    tracep->declQuad(c+254,"cached_ascii_instr", false,-1, 63,0);
    tracep->declBus(c+256,"cached_insn_imm", false,-1, 31,0);
    tracep->declBus(c+257,"cached_insn_opcode", false,-1, 31,0);
    tracep->declBus(c+258,"cached_insn_rs1", false,-1, 4,0);
    tracep->declBus(c+259,"cached_insn_rs2", false,-1, 4,0);
    tracep->declBus(c+260,"cached_insn_rd", false,-1, 4,0);
    tracep->declBus(c+343,"cpu_state_trap", false,-1, 7,0);
    tracep->declBus(c+344,"cpu_state_fetch", false,-1, 7,0);
    tracep->declBus(c+345,"cpu_state_ld_rs1", false,-1, 7,0);
    tracep->declBus(c+346,"cpu_state_ld_rs2", false,-1, 7,0);
    tracep->declBus(c+347,"cpu_state_exec", false,-1, 7,0);
    tracep->declBus(c+348,"cpu_state_shift", false,-1, 7,0);
    tracep->declBus(c+349,"cpu_state_stmem", false,-1, 7,0);
    tracep->declBus(c+350,"cpu_state_ldmem", false,-1, 7,0);
    tracep->declBus(c+261,"cpu_state", false,-1, 7,0);
    tracep->declBus(c+262,"irq_state", false,-1, 1,0);
    tracep->declArray(c+263,"dbg_ascii_state", false,-1, 127,0);
    tracep->declBit(c+267,"set_mem_do_rinst", false,-1);
    tracep->declBit(c+268,"set_mem_do_rdata", false,-1);
    tracep->declBit(c+269,"set_mem_do_wdata", false,-1);
    tracep->declBit(c+270,"latched_store", false,-1);
    tracep->declBit(c+271,"latched_stalu", false,-1);
    tracep->declBit(c+272,"latched_branch", false,-1);
    tracep->declBit(c+273,"latched_compr", false,-1);
    tracep->declBit(c+274,"latched_trace", false,-1);
    tracep->declBit(c+275,"latched_is_lu", false,-1);
    tracep->declBit(c+276,"latched_is_lh", false,-1);
    tracep->declBit(c+277,"latched_is_lb", false,-1);
    tracep->declBus(c+278,"latched_rd", false,-1, 4,0);
    tracep->declBus(c+279,"current_pc", false,-1, 31,0);
    tracep->declBus(c+351,"pcpi_timeout_counter", false,-1, 3,0);
    tracep->declBit(c+280,"pcpi_timeout", false,-1);
    tracep->declBus(c+281,"next_irq_pending", false,-1, 31,0);
    tracep->declBit(c+282,"do_waitirq", false,-1);
    tracep->declBus(c+283,"alu_out", false,-1, 31,0);
    tracep->declBus(c+284,"alu_out_q", false,-1, 31,0);
    tracep->declBit(c+285,"alu_out_0", false,-1);
    tracep->declBit(c+286,"alu_out_0_q", false,-1);
    tracep->declBit(c+287,"alu_wait", false,-1);
    tracep->declBit(c+288,"alu_wait_2", false,-1);
    tracep->declBus(c+289,"alu_add_sub", false,-1, 31,0);
    tracep->declBus(c+290,"alu_shl", false,-1, 31,0);
    tracep->declBus(c+291,"alu_shr", false,-1, 31,0);
    tracep->declBit(c+292,"alu_eq", false,-1);
    tracep->declBit(c+293,"alu_ltu", false,-1);
    tracep->declBit(c+294,"alu_lts", false,-1);
    tracep->declBit(c+295,"clear_prefetched_high_word_q", false,-1);
    tracep->declBit(c+296,"cpuregs_write", false,-1);
    tracep->declBus(c+297,"cpuregs_wrdata", false,-1, 31,0);
    tracep->declBus(c+298,"cpuregs_rs1", false,-1, 31,0);
    tracep->declBus(c+299,"cpuregs_rs2", false,-1, 31,0);
    tracep->declBus(c+352,"decoded_rs", false,-1, 4,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("u_rom ");
    tracep->declBus(c+353,"MEM_DEPTH", false,-1, 31,0);
    tracep->declQuad(c+354,"INIT_FILE", false,-1, 55,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBit(c+82,"mem_valid", false,-1);
    tracep->declBit(c+49,"mem_ready", false,-1);
    tracep->declBus(c+79,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+50,"mem_rdata", false,-1, 31,0);
    tracep->declBus(c+1,"ii", false,-1, 31,0);
    tracep->pushNamePrefix("rom_init ");
    tracep->declArray(c+2,"rom_path", false,-1, 1023,0);
    tracep->popNamePrefix(2);
    tracep->pushNamePrefix("u_sram ");
    tracep->declBus(c+356,"MEM_DEPTH", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBit(c+83,"mem_valid", false,-1);
    tracep->declBit(c+51,"mem_ready", false,-1);
    tracep->declBus(c+79,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+80,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+81,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+52,"mem_rdata", false,-1, 31,0);
    tracep->declBus(c+300,"widx", false,-1, 5,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("u_uart ");
    tracep->declBus(c+357,"CLK_FREQ", false,-1, 31,0);
    tracep->declBus(c+358,"BAUD_RATE", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBit(c+84,"mem_valid", false,-1);
    tracep->declBit(c+53,"mem_ready", false,-1);
    tracep->declBus(c+79,"mem_addr", false,-1, 31,0);
    tracep->declBus(c+80,"mem_wdata", false,-1, 31,0);
    tracep->declBus(c+81,"mem_wstrb", false,-1, 3,0);
    tracep->declBus(c+54,"mem_rdata", false,-1, 31,0);
    tracep->declBit(c+48,"uart_tx", false,-1);
    tracep->declBit(c+322,"uart_rx", false,-1);
    tracep->declBus(c+55,"tx_data", false,-1, 7,0);
    tracep->declBit(c+56,"tx_valid", false,-1);
    tracep->declBit(c+57,"tx_ready", false,-1);
    tracep->declBit(c+48,"tx_serial_out", false,-1);
    tracep->declBus(c+58,"rx_data_raw", false,-1, 7,0);
    tracep->declBit(c+59,"rx_data_valid_pulse", false,-1);
    tracep->declBus(c+301,"reg_sel", false,-1, 1,0);
    tracep->declBit(c+302,"is_write", false,-1);
    tracep->declBit(c+303,"is_read", false,-1);
    tracep->declBus(c+304,"wr_byte", false,-1, 7,0);
    tracep->declBus(c+60,"rx_buf_data", false,-1, 7,0);
    tracep->declBit(c+61,"rx_buf_valid", false,-1);
    tracep->declBit(c+62,"rx_rd_strobe", false,-1);
    tracep->declBus(c+324,"TX_IDLE", false,-1, 0,0);
    tracep->declBus(c+323,"TX_WAIT", false,-1, 0,0);
    tracep->declBit(c+63,"wr_state", false,-1);
    tracep->declBus(c+64,"wr_pending_data", false,-1, 7,0);
    tracep->declBus(c+65,"tx_buf_data", false,-1, 7,0);
    tracep->declBit(c+66,"tx_buf_valid", false,-1);
    tracep->pushNamePrefix("u_rx ");
    tracep->declBus(c+357,"CLK_FREQ", false,-1, 31,0);
    tracep->declBus(c+358,"BAUD_RATE", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBit(c+322,"rx", false,-1);
    tracep->declBus(c+58,"data_out", false,-1, 7,0);
    tracep->declBit(c+59,"data_valid", false,-1);
    tracep->declBus(c+359,"CLKS_PER_BIT", false,-1, 31,0);
    tracep->declBus(c+360,"CLKS_HALF_BIT", false,-1, 31,0);
    tracep->declBus(c+361,"CNT_WIDTH", false,-1, 31,0);
    tracep->declBus(c+362,"IDLE", false,-1, 1,0);
    tracep->declBus(c+363,"START", false,-1, 1,0);
    tracep->declBus(c+364,"DATA", false,-1, 1,0);
    tracep->declBus(c+365,"STOP", false,-1, 1,0);
    tracep->declBit(c+67,"rx_sync0", false,-1);
    tracep->declBit(c+68,"rx_sync1", false,-1);
    tracep->declBit(c+68,"rx_s", false,-1);
    tracep->declBus(c+69,"state", false,-1, 1,0);
    tracep->declBus(c+70,"clk_cnt", false,-1, 8,0);
    tracep->declBus(c+71,"bit_cnt", false,-1, 2,0);
    tracep->declBus(c+72,"shift_reg", false,-1, 7,0);
    tracep->popNamePrefix(1);
    tracep->pushNamePrefix("u_tx ");
    tracep->declBus(c+357,"CLK_FREQ", false,-1, 31,0);
    tracep->declBus(c+358,"BAUD_RATE", false,-1, 31,0);
    tracep->declBit(c+309,"clk", false,-1);
    tracep->declBit(c+310,"reset", false,-1);
    tracep->declBus(c+55,"data", false,-1, 7,0);
    tracep->declBit(c+56,"valid", false,-1);
    tracep->declBit(c+57,"ready", false,-1);
    tracep->declBit(c+48,"tx", false,-1);
    tracep->declBus(c+359,"CLKS_PER_BIT", false,-1, 31,0);
    tracep->declBus(c+361,"CNT_WIDTH", false,-1, 31,0);
    tracep->declBus(c+362,"IDLE", false,-1, 1,0);
    tracep->declBus(c+363,"START", false,-1, 1,0);
    tracep->declBus(c+364,"DATA", false,-1, 1,0);
    tracep->declBus(c+365,"STOP", false,-1, 1,0);
    tracep->declBus(c+73,"state", false,-1, 1,0);
    tracep->declBus(c+74,"shift_reg", false,-1, 7,0);
    tracep->declBus(c+75,"bit_cnt", false,-1, 2,0);
    tracep->declBus(c+76,"clk_cnt", false,-1, 8,0);
    tracep->popNamePrefix(4);
}

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_init_top(Vtb_mem_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_mem_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_mem_soc___024root__trace_init_top\n"); );
    // Body
    Vtb_mem_soc___024root__trace_init_sub__TOP__0(vlSelf, tracep);
}

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtb_mem_soc___024root__trace_chg_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp);
void Vtb_mem_soc___024root__trace_cleanup(void* voidSelf, VerilatedVcd* /*unused*/);

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_register(Vtb_mem_soc___024root* vlSelf, VerilatedVcd* tracep) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_mem_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_mem_soc___024root__trace_register\n"); );
    // Body
    tracep->addFullCb(&Vtb_mem_soc___024root__trace_full_top_0, vlSelf);
    tracep->addChgCb(&Vtb_mem_soc___024root__trace_chg_top_0, vlSelf);
    tracep->addCleanupCb(&Vtb_mem_soc___024root__trace_cleanup, vlSelf);
}

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_full_sub_0(Vtb_mem_soc___024root* vlSelf, VerilatedVcd::Buffer* bufp);

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_full_top_0(void* voidSelf, VerilatedVcd::Buffer* bufp) {
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_mem_soc___024root__trace_full_top_0\n"); );
    // Init
    Vtb_mem_soc___024root* const __restrict vlSelf VL_ATTR_UNUSED = static_cast<Vtb_mem_soc___024root*>(voidSelf);
    Vtb_mem_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    // Body
    Vtb_mem_soc___024root__trace_full_sub_0((&vlSymsp->TOP), bufp);
}

VL_ATTR_COLD void Vtb_mem_soc___024root__trace_full_sub_0(Vtb_mem_soc___024root* vlSelf, VerilatedVcd::Buffer* bufp) {
    if (false && vlSelf) {}  // Prevent unused
    Vtb_mem_soc__Syms* const __restrict vlSymsp VL_ATTR_UNUSED = vlSelf->vlSymsp;
    VL_DEBUG_IF(VL_DBG_MSGF("+    Vtb_mem_soc___024root__trace_full_sub_0\n"); );
    // Init
    uint32_t* const oldp VL_ATTR_UNUSED = bufp->oldp(vlSymsp->__Vm_baseCode);
    // Body
    bufp->fullIData(oldp+1,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_rom__DOT__ii),32);
    bufp->fullWData(oldp+2,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_rom__DOT__rom_init__DOT__rom_path),1024);
    bufp->fullIData(oldp+34,(vlSelf->tb_mem_soc__DOT__greeting_count),32);
    bufp->fullIData(oldp+35,(vlSelf->tb_mem_soc__DOT__line_count),32);
    bufp->fullIData(oldp+36,(vlSelf->tb_mem_soc__DOT__rx_wr_ptr),32);
    bufp->fullCData(oldp+37,(vlSelf->tb_mem_soc__DOT__mon_byte),8);
    bufp->fullIData(oldp+38,(vlSelf->tb_mem_soc__DOT__bit_idx),32);
    bufp->fullWData(oldp+39,(vlSelf->tb_mem_soc__DOT__asm_line),256);
    bufp->fullIData(oldp+47,(vlSelf->tb_mem_soc__DOT__asm_len),32);
    bufp->fullBit(oldp+48,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__tx_serial_out));
    bufp->fullBit(oldp+49,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__rom_ready));
    bufp->fullIData(oldp+50,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__rom_rdata),32);
    bufp->fullBit(oldp+51,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sram_ready));
    bufp->fullIData(oldp+52,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sram_rdata),32);
    bufp->fullBit(oldp+53,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__uart_ready));
    bufp->fullIData(oldp+54,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__uart_rdata),32);
    bufp->fullCData(oldp+55,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__tx_data),8);
    bufp->fullBit(oldp+56,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__tx_valid));
    bufp->fullBit(oldp+57,((0U == (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_tx__DOT__state))));
    bufp->fullCData(oldp+58,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__rx_data_raw),8);
    bufp->fullBit(oldp+59,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__rx_data_valid_pulse));
    bufp->fullCData(oldp+60,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__rx_buf_data),8);
    bufp->fullBit(oldp+61,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__rx_buf_valid));
    bufp->fullBit(oldp+62,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__rx_rd_strobe));
    bufp->fullBit(oldp+63,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__wr_state));
    bufp->fullCData(oldp+64,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__wr_pending_data),8);
    bufp->fullCData(oldp+65,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__tx_buf_data),8);
    bufp->fullBit(oldp+66,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__tx_buf_valid));
    bufp->fullBit(oldp+67,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__rx_sync0));
    bufp->fullBit(oldp+68,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__rx_sync1));
    bufp->fullCData(oldp+69,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__state),2);
    bufp->fullSData(oldp+70,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__clk_cnt),9);
    bufp->fullCData(oldp+71,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__bit_cnt),3);
    bufp->fullCData(oldp+72,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_rx__DOT__shift_reg),8);
    bufp->fullCData(oldp+73,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_tx__DOT__state),2);
    bufp->fullCData(oldp+74,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_tx__DOT__shift_reg),8);
    bufp->fullCData(oldp+75,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_tx__DOT__bit_cnt),3);
    bufp->fullSData(oldp+76,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__u_tx__DOT__clk_cnt),9);
    bufp->fullBit(oldp+77,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_valid));
    bufp->fullBit(oldp+78,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_instr));
    bufp->fullIData(oldp+79,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_addr),32);
    bufp->fullIData(oldp+80,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_wdata),32);
    bufp->fullCData(oldp+81,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_wstrb),4);
    bufp->fullBit(oldp+82,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sel_rom));
    bufp->fullBit(oldp+83,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sel_sram));
    bufp->fullBit(oldp+84,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sel_uart));
    bufp->fullBit(oldp+85,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__trap));
    bufp->fullIData(oldp+86,((((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_prefetch) 
                               | (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_rinst))
                               ? (0xfffffffcU & vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__next_pc)
                               : (0xfffffffcU & vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1))),32);
    bufp->fullIData(oldp+87,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_wdata),32);
    bufp->fullCData(oldp+88,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_wstrb),4);
    bufp->fullBit(oldp+89,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__pcpi_valid));
    bufp->fullIData(oldp+90,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__pcpi_insn),32);
    bufp->fullIData(oldp+91,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1),32);
    bufp->fullIData(oldp+92,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op2),32);
    bufp->fullIData(oldp+93,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__eoi),32);
    bufp->fullBit(oldp+94,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__trace_valid));
    bufp->fullQData(oldp+95,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__trace_data),36);
    bufp->fullQData(oldp+97,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__count_cycle),64);
    bufp->fullQData(oldp+99,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__count_instr),64);
    bufp->fullIData(oldp+101,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_pc),32);
    bufp->fullIData(oldp+102,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_next_pc),32);
    bufp->fullIData(oldp+103,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_out),32);
    bufp->fullCData(oldp+104,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_sh),5);
    bufp->fullIData(oldp+105,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__next_insn_opcode),32);
    bufp->fullIData(oldp+106,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_opcode),32);
    bufp->fullIData(oldp+107,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_addr),32);
    bufp->fullIData(oldp+108,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__next_pc),32);
    bufp->fullBit(oldp+109,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__irq_delay));
    bufp->fullBit(oldp+110,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__irq_active));
    bufp->fullIData(oldp+111,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__irq_mask),32);
    bufp->fullIData(oldp+112,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__irq_pending),32);
    bufp->fullIData(oldp+113,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__timer),32);
    bufp->fullIData(oldp+114,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[0]),32);
    bufp->fullIData(oldp+115,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[1]),32);
    bufp->fullIData(oldp+116,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[2]),32);
    bufp->fullIData(oldp+117,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[3]),32);
    bufp->fullIData(oldp+118,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[4]),32);
    bufp->fullIData(oldp+119,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[5]),32);
    bufp->fullIData(oldp+120,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[6]),32);
    bufp->fullIData(oldp+121,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[7]),32);
    bufp->fullIData(oldp+122,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[8]),32);
    bufp->fullIData(oldp+123,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[9]),32);
    bufp->fullIData(oldp+124,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[10]),32);
    bufp->fullIData(oldp+125,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[11]),32);
    bufp->fullIData(oldp+126,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[12]),32);
    bufp->fullIData(oldp+127,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[13]),32);
    bufp->fullIData(oldp+128,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[14]),32);
    bufp->fullIData(oldp+129,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[15]),32);
    bufp->fullIData(oldp+130,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[16]),32);
    bufp->fullIData(oldp+131,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[17]),32);
    bufp->fullIData(oldp+132,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[18]),32);
    bufp->fullIData(oldp+133,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[19]),32);
    bufp->fullIData(oldp+134,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[20]),32);
    bufp->fullIData(oldp+135,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[21]),32);
    bufp->fullIData(oldp+136,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[22]),32);
    bufp->fullIData(oldp+137,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[23]),32);
    bufp->fullIData(oldp+138,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[24]),32);
    bufp->fullIData(oldp+139,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[25]),32);
    bufp->fullIData(oldp+140,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[26]),32);
    bufp->fullIData(oldp+141,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[27]),32);
    bufp->fullIData(oldp+142,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[28]),32);
    bufp->fullIData(oldp+143,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[29]),32);
    bufp->fullIData(oldp+144,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[30]),32);
    bufp->fullIData(oldp+145,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs[31]),32);
    bufp->fullCData(oldp+146,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_state),2);
    bufp->fullCData(oldp+147,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_wordsize),2);
    bufp->fullIData(oldp+148,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_rdata_q),32);
    bufp->fullBit(oldp+149,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_prefetch));
    bufp->fullBit(oldp+150,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_rinst));
    bufp->fullBit(oldp+151,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_rdata));
    bufp->fullBit(oldp+152,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_wdata));
    bufp->fullBit(oldp+153,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_secondword));
    bufp->fullBit(oldp+154,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_firstword_reg));
    bufp->fullBit(oldp+155,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__last_mem_valid));
    bufp->fullBit(oldp+156,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__prefetched_high_word));
    bufp->fullBit(oldp+157,(((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_do_prefetch) 
                             | (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT____VdfgTmp_hb06275b1__0))));
    bufp->fullBit(oldp+158,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lui));
    bufp->fullBit(oldp+159,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_auipc));
    bufp->fullBit(oldp+160,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_jal));
    bufp->fullBit(oldp+161,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_jalr));
    bufp->fullBit(oldp+162,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_beq));
    bufp->fullBit(oldp+163,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_bne));
    bufp->fullBit(oldp+164,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_blt));
    bufp->fullBit(oldp+165,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_bge));
    bufp->fullBit(oldp+166,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_bltu));
    bufp->fullBit(oldp+167,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_bgeu));
    bufp->fullBit(oldp+168,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lb));
    bufp->fullBit(oldp+169,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lh));
    bufp->fullBit(oldp+170,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lw));
    bufp->fullBit(oldp+171,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lbu));
    bufp->fullBit(oldp+172,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_lhu));
    bufp->fullBit(oldp+173,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sb));
    bufp->fullBit(oldp+174,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sh));
    bufp->fullBit(oldp+175,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sw));
    bufp->fullBit(oldp+176,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_addi));
    bufp->fullBit(oldp+177,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_slti));
    bufp->fullBit(oldp+178,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sltiu));
    bufp->fullBit(oldp+179,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_xori));
    bufp->fullBit(oldp+180,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_ori));
    bufp->fullBit(oldp+181,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_andi));
    bufp->fullBit(oldp+182,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_slli));
    bufp->fullBit(oldp+183,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_srli));
    bufp->fullBit(oldp+184,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_srai));
    bufp->fullBit(oldp+185,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_add));
    bufp->fullBit(oldp+186,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sub));
    bufp->fullBit(oldp+187,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sll));
    bufp->fullBit(oldp+188,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_slt));
    bufp->fullBit(oldp+189,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sltu));
    bufp->fullBit(oldp+190,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_xor));
    bufp->fullBit(oldp+191,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_srl));
    bufp->fullBit(oldp+192,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sra));
    bufp->fullBit(oldp+193,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_or));
    bufp->fullBit(oldp+194,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_and));
    bufp->fullBit(oldp+195,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_rdcycle));
    bufp->fullBit(oldp+196,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_rdcycleh));
    bufp->fullBit(oldp+197,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_rdinstr));
    bufp->fullBit(oldp+198,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_rdinstrh));
    bufp->fullBit(oldp+199,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_ecall_ebreak));
    bufp->fullBit(oldp+200,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_fence));
    bufp->fullBit(oldp+201,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_getq));
    bufp->fullBit(oldp+202,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_setq));
    bufp->fullBit(oldp+203,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__compressed_instr));
    bufp->fullBit(oldp+204,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_maskirq));
    bufp->fullBit(oldp+205,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_waitirq));
    bufp->fullBit(oldp+206,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_timer));
    bufp->fullBit(oldp+207,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_trap));
    bufp->fullCData(oldp+208,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoded_rd),5);
    bufp->fullCData(oldp+209,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoded_rs1),5);
    bufp->fullCData(oldp+210,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoded_rs2),5);
    bufp->fullIData(oldp+211,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoded_imm),32);
    bufp->fullIData(oldp+212,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoded_imm_j),32);
    bufp->fullBit(oldp+213,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoder_trigger));
    bufp->fullBit(oldp+214,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoder_trigger_q));
    bufp->fullBit(oldp+215,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoder_pseudo_trigger));
    bufp->fullBit(oldp+216,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__decoder_pseudo_trigger_q));
    bufp->fullBit(oldp+217,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_lui_auipc_jal));
    bufp->fullBit(oldp+218,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_lb_lh_lw_lbu_lhu));
    bufp->fullBit(oldp+219,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_slli_srli_srai));
    bufp->fullBit(oldp+220,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_jalr_addi_slti_sltiu_xori_ori_andi));
    bufp->fullBit(oldp+221,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_sb_sh_sw));
    bufp->fullBit(oldp+222,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_sll_srl_sra));
    bufp->fullBit(oldp+223,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_lui_auipc_jal_jalr_addi_add_sub));
    bufp->fullBit(oldp+224,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_slti_blt_slt));
    bufp->fullBit(oldp+225,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_sltiu_bltu_sltu));
    bufp->fullBit(oldp+226,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_beq_bne_blt_bge_bltu_bgeu));
    bufp->fullBit(oldp+227,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_lbu_lhu_lw));
    bufp->fullBit(oldp+228,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_alu_reg_imm));
    bufp->fullBit(oldp+229,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_alu_reg_reg));
    bufp->fullBit(oldp+230,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_compare));
    bufp->fullBit(oldp+231,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__is_rdcycle_rdcycleh_rdinstr_rdinstrh));
    bufp->fullQData(oldp+232,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__new_ascii_instr),64);
    bufp->fullQData(oldp+234,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_ascii_instr),64);
    bufp->fullIData(oldp+236,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_imm),32);
    bufp->fullCData(oldp+237,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_rs1),5);
    bufp->fullCData(oldp+238,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_rs2),5);
    bufp->fullCData(oldp+239,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_insn_rd),5);
    bufp->fullIData(oldp+240,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_rs1val),32);
    bufp->fullIData(oldp+241,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_rs2val),32);
    bufp->fullBit(oldp+242,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_rs1val_valid));
    bufp->fullBit(oldp+243,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_rs2val_valid));
    bufp->fullQData(oldp+244,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_ascii_instr),64);
    bufp->fullIData(oldp+246,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_insn_imm),32);
    bufp->fullIData(oldp+247,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_insn_opcode),32);
    bufp->fullCData(oldp+248,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_insn_rs1),5);
    bufp->fullCData(oldp+249,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_insn_rs2),5);
    bufp->fullCData(oldp+250,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__q_insn_rd),5);
    bufp->fullBit(oldp+251,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_next));
    bufp->fullBit(oldp+252,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__launch_next_insn));
    bufp->fullBit(oldp+253,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_valid_insn));
    bufp->fullQData(oldp+254,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_ascii_instr),64);
    bufp->fullIData(oldp+256,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_insn_imm),32);
    bufp->fullIData(oldp+257,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_insn_opcode),32);
    bufp->fullCData(oldp+258,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_insn_rs1),5);
    bufp->fullCData(oldp+259,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_insn_rs2),5);
    bufp->fullCData(oldp+260,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cached_insn_rd),5);
    bufp->fullCData(oldp+261,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpu_state),8);
    bufp->fullCData(oldp+262,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__irq_state),2);
    bufp->fullWData(oldp+263,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_ascii_state),128);
    bufp->fullBit(oldp+267,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__set_mem_do_rinst));
    bufp->fullBit(oldp+268,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__set_mem_do_rdata));
    bufp->fullBit(oldp+269,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__set_mem_do_wdata));
    bufp->fullBit(oldp+270,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_store));
    bufp->fullBit(oldp+271,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_stalu));
    bufp->fullBit(oldp+272,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_branch));
    bufp->fullBit(oldp+273,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_compr));
    bufp->fullBit(oldp+274,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_trace));
    bufp->fullBit(oldp+275,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_is_lu));
    bufp->fullBit(oldp+276,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_is_lh));
    bufp->fullBit(oldp+277,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_is_lb));
    bufp->fullCData(oldp+278,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__latched_rd),5);
    bufp->fullIData(oldp+279,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__current_pc),32);
    bufp->fullBit(oldp+280,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__pcpi_timeout));
    bufp->fullIData(oldp+281,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__next_irq_pending),32);
    bufp->fullBit(oldp+282,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__do_waitirq));
    bufp->fullIData(oldp+283,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_out),32);
    bufp->fullIData(oldp+284,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_out_q),32);
    bufp->fullBit(oldp+285,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_out_0));
    bufp->fullBit(oldp+286,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_out_0_q));
    bufp->fullBit(oldp+287,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_wait));
    bufp->fullBit(oldp+288,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_wait_2));
    bufp->fullIData(oldp+289,(((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sub)
                                ? (vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1 
                                   - vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op2)
                                : (vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1 
                                   + vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+290,((vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1 
                               << (0x1fU & vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op2))),32);
    bufp->fullIData(oldp+291,((IData)((0x1ffffffffULL 
                                       & VL_SHIFTRS_QQI(33,33,5, 
                                                        (((QData)((IData)(
                                                                          (((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_sra) 
                                                                            | (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__instr_srai)) 
                                                                           & (vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1 
                                                                              >> 0x1fU)))) 
                                                          << 0x20U) 
                                                         | (QData)((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op1))), 
                                                        (0x1fU 
                                                         & vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__reg_op2))))),32);
    bufp->fullBit(oldp+292,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_eq));
    bufp->fullBit(oldp+293,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_ltu));
    bufp->fullBit(oldp+294,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__alu_lts));
    bufp->fullBit(oldp+295,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__clear_prefetched_high_word_q));
    bufp->fullBit(oldp+296,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs_write));
    bufp->fullIData(oldp+297,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs_wrdata),32);
    bufp->fullIData(oldp+298,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs_rs1),32);
    bufp->fullIData(oldp+299,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__cpuregs_rs2),32);
    bufp->fullCData(oldp+300,((0x3fU & (vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_addr 
                                        >> 2U))),6);
    bufp->fullCData(oldp+301,((3U & (vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_addr 
                                     >> 2U))),2);
    bufp->fullBit(oldp+302,(((IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sel_uart) 
                             & (0U != (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_wstrb)))));
    bufp->fullBit(oldp+303,(((~ (IData)((0U != (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__cpu_mem_wstrb)))) 
                             & (IData)(vlSelf->tb_mem_soc__DOT__u_dut__DOT__sel_uart))));
    bufp->fullCData(oldp+304,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_uart__DOT__wr_byte),8);
    bufp->fullIData(oldp+305,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_mem_rdata),32);
    bufp->fullIData(oldp+306,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_rdata_word),32);
    bufp->fullBit(oldp+307,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_xfer));
    bufp->fullIData(oldp+308,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_rdata_latched_noshuffle),32);
    bufp->fullBit(oldp+309,(vlSelf->tb_mem_soc__DOT__clk));
    bufp->fullBit(oldp+310,(vlSelf->tb_mem_soc__DOT__reset));
    bufp->fullBit(oldp+311,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__dbg_mem_ready));
    bufp->fullBit(oldp+312,((1U & (~ (IData)(vlSelf->tb_mem_soc__DOT__reset)))));
    bufp->fullBit(oldp+313,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_read));
    bufp->fullBit(oldp+314,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_la_write));
    bufp->fullBit(oldp+315,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__clear_prefetched_high_word));
    bufp->fullBit(oldp+316,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_done));
    bufp->fullIData(oldp+317,(0x14U),32);
    bufp->fullIData(oldp+318,(0x1b2U),32);
    bufp->fullIData(oldp+319,(0x10f4U),32);
    bufp->fullIData(oldp+320,(0x21e8U),32);
    bufp->fullIData(oldp+321,(0x77359400U),32);
    bufp->fullBit(oldp+322,(1U));
    bufp->fullBit(oldp+323,(1U));
    bufp->fullBit(oldp+324,(0U));
    bufp->fullIData(oldp+325,(0U),32);
    bufp->fullIData(oldp+326,(0xffffffffU),32);
    bufp->fullIData(oldp+327,(0x10U),32);
    bufp->fullIData(oldp+328,(0x100fcU),32);
    bufp->fullBit(oldp+329,(0U));
    bufp->fullIData(oldp+330,(0U),32);
    bufp->fullIData(oldp+331,(1U),32);
    bufp->fullIData(oldp+332,(2U),32);
    bufp->fullIData(oldp+333,(0x20U),32);
    bufp->fullIData(oldp+334,(5U),32);
    bufp->fullQData(oldp+335,(0x100000000ULL),36);
    bufp->fullQData(oldp+337,(0x200000000ULL),36);
    bufp->fullQData(oldp+339,(0x800000000ULL),36);
    bufp->fullIData(oldp+341,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__i),32);
    bufp->fullSData(oldp+342,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__mem_16bit_buffer),16);
    bufp->fullCData(oldp+343,(0x80U),8);
    bufp->fullCData(oldp+344,(0x40U),8);
    bufp->fullCData(oldp+345,(0x20U),8);
    bufp->fullCData(oldp+346,(0x10U),8);
    bufp->fullCData(oldp+347,(8U),8);
    bufp->fullCData(oldp+348,(4U),8);
    bufp->fullCData(oldp+349,(2U),8);
    bufp->fullCData(oldp+350,(1U),8);
    bufp->fullCData(oldp+351,(vlSelf->tb_mem_soc__DOT__u_dut__DOT__u_cpu__DOT__pcpi_timeout_counter),4);
    bufp->fullCData(oldp+352,(0U),5);
    bufp->fullIData(oldp+353,(0x800U),32);
    bufp->fullQData(oldp+354,(0x726f6d2e686578ULL),56);
    bufp->fullIData(oldp+356,(0x40U),32);
    bufp->fullIData(oldp+357,(0x2faf080U),32);
    bufp->fullIData(oldp+358,(0x1c200U),32);
    bufp->fullIData(oldp+359,(0x1b2U),32);
    bufp->fullIData(oldp+360,(0xd9U),32);
    bufp->fullIData(oldp+361,(9U),32);
    bufp->fullCData(oldp+362,(0U),2);
    bufp->fullCData(oldp+363,(1U),2);
    bufp->fullCData(oldp+364,(2U),2);
    bufp->fullCData(oldp+365,(3U),2);
}
